### ISSUE TITLE
Using defaults doesnt work

### ISSUE THREAD

**Issue by kavitama** [pentium10/yii-remember-filters-gridview#3]
My model:
<pre>
	public function behaviors()
	{
		return array_merge(
			array(
				'datetimeI18NBehavior' => array(
					'class' => 'ext.DateTime.DateTimeI18NBehavior'
				),
				'ERememberFiltersBehavior' => array(
					'class' => 'application.components.ERememberFiltersBehavior',
					'defaults'=>array('way_status_id' => 1),           /* optional line */
					'defaultStickOnClear'=>true   /* optional line */
				),
			), 
			parent::behaviors()
		);
	}
</pre>
My controller:
<pre>
	public function actionAdmin()
	{
		$model = new OneWay('search');
		$model->setRememberScenario('actionAdmin');
		if (intval(Yii::app()->request->getParam('clearFilters'))==1) 
			{ EButtonColumnWithClearFilters::clearFilters($this,$model); /* where $this is the controller */}
		$this->render(
			'admin', 
			array(
				'model' => $model,
			)
		);
	}
</pre>
My View:
<pre>
<?php
	/** @var OneWayController $this */
	/** @var OneWay $model */
	$this->widget(
		'bootstrap.widgets.TbBreadcrumbs',
		array(
			'links' => array(
				Yii::t('AweCrud.app', 'Manage').' '.OneWay::label(2), 
			),
		)
	);
?>

<fieldset>
	<legend><?php echo Yii::t('AweCrud.app', 'Manage') ?> <?php echo OneWay::label(2) ?></legend>

	<?php
		$this->beginWidget('zii.widgets.CPortlet', array('htmlOptions'=>array('class'=>'')));
		$this->widget('bootstrap.widgets.TbMenu', 
			array(
				'type'=>'pills',
				'items'=>array(
					array(
						'label'=>Yii::t('app', 'clearFilters'),
						'icon'=>'search', 
						'url'=> Yii::app()->controller->createUrl(Yii::app()->controller->action->ID,array("clearFilters"=>1)),
						'active'=>true, 
						'linkOptions'=>array(
							'class'=>'btn btn-info btn-small'
						)
					),
					array(
						'label'=>Yii::t('app', 'pdfToday'),
						'icon'=>'file', 
						'url' => Yii::app()->createUrl(
							"reportico/mode/execute", 
							array(
								'project' => 'GTV54 - Listados para Empleados', 
								'report' => 'Listado Viajes por Chofer (Hoy).xml',
								'partialReportico' => '1',
								'target_format' => 'PDF'
							)
						),
						'active'=>true, 
						'linkOptions'=>array(
							'class'=>'btn btn-info btn-small',
						)
					),
					array(
						'label'=>Yii::t('app', 'pdfTomorrow'),
						'icon'=>'file', 
						'url' => Yii::app()->createUrl(
							"reportico/mode/execute", 
							array(
								'project' => 'GTV54 - Listados para Empleados', 
								'report' => 'Listado Viajes por Chofer (Mañana).xml',
								'partialReportico' => '1',
								'target_format' => 'PDF'
							)
						),
						'active'=>true, 
						'linkOptions'=>array(
							'class'=>'btn btn-info btn-small',
						)
					),
				),
			)
		);
		$this->endWidget();
    ?>

<?php 
	$this->widget('bootstrap.widgets.TbExtendedGridView',
		array(
			//'fixedHeader' => true,
			//'headerOffset' => 40,
			'responsiveTable' => true,
			'template' => "{pager}\n{summary}\n{items}\n{pager}",
			'id' => 'one-way-grid',
			'type' => 'striped bordered condensed',
			'dataProvider' => $model->search(),
			'filter' => $model,
			'afterAjaxUpdate' => 'reinstallDatePicker',
			'columns' => array(
				array(
					'class'=>'bootstrap.widgets.TbButtonColumn',
					'header' => Yii::t('app', 'reservationsShort'),
					'template'=>'{reservationsCalls} {reservationsList} {printReservation} {reservationsQuery} {reservationsMove}',
					'buttons'=>array(
						'reservationsCalls' => array(
							'label'=>Yii::t('app', 'reservationsCalls'),
							'icon'=>'phone',
							'url'=>'Yii::app()->createUrl("OnePassenger/select", array("caller"=>"reservationsCalls", "way_id"=>$data->id))',
							'options'=>array('class'=>'btn btn-info',),
							'visible' => '$data->way_status_id == 1',
						),
						'reservationsList' => array(
							'label'=>Yii::t('app', 'reservationsList'),
							'icon'=>'th-list',
							'url'=>'Yii::app()->createUrl("OneWayReservation/admin", array("id"=>$data->id))',
							'options'=>array('class'=>'btn btn-info',),
							'visible' => '$data->way_status_id == 1',
						),
						'printReservation' => array(
							'label'=>Yii::t('app', 'printReservation'),
							'icon'=>'print',
							'url'=>'
								Yii::app()->createUrl(
									"reportico/mode/execute", 
									array(
										"project" => "GTV54 - Listados para Empleados", 
										"report" => "Listado Reservas.xml",
										"partialReportico" => "1",
										"target_format" => "PDF", 
										"MANUAL_id" => "$data->id"
									)
								)
							',
							'options'=>array('class'=>'btn btn-info',),
							'visible' => '$data->way_status_id == 1',
						),
						'reservationsQuery' => array(
							'label'=>Yii::t('app', 'reservationsList'),
							'icon'=>'th-list',
							'url'=>'Yii::app()->createUrl("OneWayReservation/adminQuery", array("id"=>$data->id))',
							'options'=>array('class'=>'btn btn-info',),
							'visible' => '$data->way_status_id == 2 || $data->way_status_id == 4',
						),
						'reservationsMove' => array(
							'label'=>Yii::t('app', 'reservationsMove'),
							'icon'=>'external-link',
							'url'=>'Yii::app()->createUrl("OneWayReservation/reservationMove", array("wid"=>$data->id))',
							'visible' => 'OneWay::findVehicleFreeSeats($data->vehicle_id, $data->id) < 0',
							'options'=>array(
								'class'=>'btn btn-danger',
								'ajax'=>array(
									'type'=>'POST',
									'url'=>"js:$(this).attr('href')",
									'success'=>'function(data) { $("#viewWays .modal-body p").html(data); $("#viewWays").modal(); }'
								), 
							),
						),
					),
//					'htmlOptions' => array('nowrap'=>'nowrap'),
					'visible' => OneCompany::isReservationEnabled() == true,
				),
				'way_date',
/*				array(
					'name' => 'way_date',
					'filter'=>$this->widget(
						'zii.widgets.jui.CJuiDatePicker', 
						array(
							'model'=>$model,
							'attribute'=>'way_date',
							'htmlOptions' => array(
								'id' => 'way_date_search'
							), 
							'options' => array(
								'dateFormat' => 'yy-mm-dd'
							)
						),
					true)
				),
*/				'way_time',
				array(
					'name' => 'vehicle_free_seats',
					'value' => 'OneWay::findVehicleFreeSeats($data->vehicle_id, $data->id)', 
					'visible' => OneCompany::isReservationEnabled() == true,
					'filter' => false,
					'htmlOptions'=>array('style' => 'text-align: right;'),
					'cssClassExpression' => 'OneWay::findVehicleFreeSeats($data->vehicle_id, $data->id) < 0 ? "yRedMarked" : ""',
                ),
				array(
                    'name' => 'route_id',
                    'value' => 'isset($data->route) ? $data->route : null',
                    'filter' => CHtml::listData(OneRoute::model()->findAll(), 'id', OneRoute::representingColumn()),
                ),
				array(
                    'name' => 'origin_id',
                    'value' => 'isset($data->origin) ? $data->origin : null',
                    'filter' => CHtml::listData(OneStop::model()->findAll(), 'id', OneStop::representingColumn()),
                ),
				array(
                    'name' => 'travel_id',
                    'value' => 'isset($data->travel) ? $data->travel : null',
                    'filter' => CHtml::listData(QryTravel::model()->findAll(), 'id', QryTravel::representingColumn()),
                ),
				array(
                    'name' => 'vehicle_id',
                    'value' => 'isset($data->vehicle) ? $data->vehicle : null',
                    'filter' => CHtml::listData(OneVehicle::model()->findAll(), 'id', OneVehicle::representingColumn()),
                ),
				array(
                    'name' => 'driver_id',
                    'value' => 'isset($data->driver) ? $data->driver : null',
                    'filter' => CHtml::listData(OneDriver::model()->findAll(), 'id', OneDriver::representingColumn()),
                ),
				array(
                    'name' => 'way_group_id',
                    'value' => 'isset($data->wayGroup) ? $data->wayGroup : null',
                    'filter' => CHtml::listData(QryWayGroup::model()->findAll(), 'id', QryWayGroup::representingColumn()),
                ),
				array(
                    'name' => 'way_status_id',
                    'value' => 'isset($data->wayStatus) ? $data->wayStatus : null',
                    'filter' => CHtml::listData(QryWayStatus::model()->findAll(), 'id', QryWayStatus::representingColumn()),
                ),
				array(
					'class'=>'bootstrap.widgets.TbButtonColumn',
					'header' => Yii::t('app', 'changeStatus'),
					'template'=>'{wayBegin} {wayCancel} {wayEnd} {wayBreak}',
					'buttons'=>array(
						'wayBegin' => array(
							'label'=>Yii::t('app', 'wayBegin'),
							'icon'=>'play',
							'url'=>'Yii::app()->createUrl("OneWay/employeeWayBegin", array("id"=>$data->id))',
							'options'=>array('class'=>'btn btn-success',),
							'visible' => '$data->way_status_id == 1 && OneWay::findVehicleFreeSeats($data->vehicle_id, $data->id) >= 0',
						),
						'wayCancel' => array(
							'label'=>Yii::t('app', 'wayCancel'),
							'icon'=>'eject',
							'url'=>'Yii::app()->createUrl("OneWay/employeeWayCancel", array("id"=>$data->id))',
							'options'=>array(
								'class'=>'btn btn-danger',
								'confirm' => Yii::t('app', 'confirmCancel?'),
							),
							'visible' => '$data->way_status_id == 1',
						),
						'wayEnd' => array(
							'label'=>Yii::t('app', 'wayEnd'),
							'icon'=>'stop',
							'url'=>'Yii::app()->createUrl("OneWay/employeeWayEnd", array("id"=>$data->id))',
							'options'=>array(
								'class'=>'btn btn-inverse',
								'confirm' => Yii::t('app', 'confirmEnd?'),
							),
							'visible' => '$data->way_status_id == 2 || $data->way_status_id == 4',
						),
						'wayBreak' => array(
							'label'=>Yii::t('app', 'wayBreak'),
							'icon'=>'step-backward',
							'url'=>'Yii::app()->createUrl("OneWay/employeeWayBreak", array("id"=>$data->id))',
							'options'=>array(
								'class'=>'btn btn-warning',
								'confirm' => Yii::t('app', 'confirmBreak?'),
							),
							'visible' => '$data->way_status_id == 2 || $data->way_status_id == 4',
						),
					),
//					'htmlOptions' => array('nowrap'=>'nowrap'),
				),
				array(
					'class'=>'bootstrap.widgets.TbButtonColumn',
					'header' => Yii::t('app', 'operations'),
					'template'=>'{update} {copy} {driverReport} {driverReportOk} {inspectorReport} {inspectorReportOk} {wayStatusReport} {vehicleSimulator}',
					'buttons'=>array(
						'update' => array(
							'options'=>array('class'=>'btn btn-info',),
							'visible' => '$data->way_status_id == 1',
						),
						'copy' => array(
							'label'=>Yii::t('app', 'copy'),
							'icon'=>'copy',
							'url'=>'Yii::app()->createUrl("OneWay/copy", array("id"=>$data->id))',
							'options'=>array('class'=>'btn btn-info',),
							'visible' => '$data->way_status_id == 1',
						),
						'driverReport' => array(
							'label'=>Yii::t('app', 'driverReport'),
							'icon'=>'dollar',
							'url'=>'Yii::app()->createUrl("OneWay/driverReportBegin", array("id"=>$data->id))',
							'options'=>array('class'=>'btn btn-danger',),
							'visible' => 'OneCompany::isReservationEnabled() == true && $data->way_status_id == 6 && $data->driver_report_ended == false',
						),
						'driverReportOk' => array(
							'label'=>Yii::t('app', 'driverReport'),
							'icon'=>'dollar',
							'url'=>'Yii::app()->createUrl("OneWay/driverReportQuery", array("id"=>$data->id))',
							'options'=>array('class'=>'btn btn-success',),
							'visible' => '(OneCompany::isReservationEnabled() == true && $data->way_status_id == 7) || (OneCompany::isReservationEnabled() == true && $data->way_status_id == 6 && $data->driver_report_ended == true)',
						),
						'inspectorReport' => array(
							'label'=>Yii::t('app', 'inspectorReport'),
							'icon'=>'user',
							'url'=>'Yii::app()->createUrl("OneWayInspection/wayAdmin", array("way_id"=>$data->id))',
							'options'=>array('class'=>'btn btn-danger',),
							'visible' => 'OneCompany::isInspectionEnabled() == true && $data->way_status_id == 6 && OneWayInspection::checkInspections($data->id)==1',
						),
						'inspectorReportOk' => array(
							'label'=>Yii::t('app', 'inspectorReport'),
							'icon'=>'user',
							'url'=>'Yii::app()->createUrl("OneWayInspection/wayQuery", array("way_id"=>$data->id))',
							'options'=>array('class'=>'btn btn-success',),
							'visible' => '(OneCompany::isInspectionEnabled() == true && $data->way_status_id == 7) || (OneCompany::isInspectionEnabled() == true && $data->way_status_id == 6 && OneWayInspection::checkInspections($data->id)==2)',
						),
						'wayStatusReport' => array(
							'label'=>Yii::t('app', 'differences'),
							'icon'=>'warning-sign',
							'url'=>'Yii::app()->createUrl("OneWay/existReportDifferences", array("id"=>$data->id))',
							'visible' => 'OneCompany::isDriverReportEnabled() == true && $data->way_status_id == 6 && $data->driver_report_ended == true && OneWayInspection::checkInspections($data->id)==2 && OneWay::existReportDifferences($data->id)==true',
							'options'=>array(
								'class'=>'btn btn-danger',
								'ajax'=>array(
									'type'=>'POST',
									'url'=>"js:$(this).attr('href')",
									'success'=>'function(data) { $("#viewModal .modal-body p").html(data); $("#viewModal").modal(); }'
								), 
							),
						),
						'vehicleSimulator' => array(
							'label'=>Yii::t('app', 'vehicleSimulator'),
							'icon'=>'credit-card',
							'url'=>'Yii::app()->createUrl("Card/simulator", array("wid"=>$data->id, "cid"=>null))',
							'options'=>array('class'=>'btn btn-large btn-danger',),
							'visible' => '$data->way_status_id == 2',
						),
					),
//					'htmlOptions' => array('nowrap'=>'nowrap'),
				),
			),
		)
	); 
Yii::app()->clientScript->registerScript('re-install-date-picker', "
    function reinstallDatePicker(id, data) {
        $('#OneWay_way_date').datepicker('option', 'dateFormat', 'yy-mm-dd');
    }
");
?>
</fieldset>

<?php
	include "_includeModalDifference.php";
	include "_includeModalReservation.php";
?>

</pre>

I cleared any cache data to be sure but no chance to see the default applied.
What am I doing wrong or where should I look at?

Regards

**Comment by pentium10** [comment]
We don't support customized gridviews like TbExtendedGridView, only Yii's CGridView.
You need to find a way to edit our extension to make it compatible with Bootstrap gridviews.
